# Generated by Django 5.0.7 on 2024-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('men', 'Men'), ('kids', 'Kids')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('packing', models.CharField(blank=True, max_length=100)),
                ('sizes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(upload_to='products/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
