# Generated by Django 5.0.7 on 2024-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Kids', 'Kids')], max_length=10),
        ),
    ]
